<?php

namespace App\Application\Logger;

class ApplicationLogger
{
    public const ERROR_BODY_REQUEST = 'ERROR_BODY_REQUEST';
    public const ERROR_AUTHOR_NOT_FOUND = 'ERROR_AUTHOR_NOT_FOUND';
    public const ERROR_ARTICLE_NOT_FOUND = 'ERROR_ARTICLE_NOT_FOUND';
    public const ERROR_ARTICLE_REQUEST_VALIDATION = 'ERROR_ARTICLE_REQUEST_VALIDATION';
    public const ERROR_ARTICLE_VALIDATION = 'ERROR_ARTICLE_VALIDATION';
}
